# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/BulkOrPlanetoid.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/BulkOrPlanetoid.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bproto/BulkOrPlanetoid.proto\"\x97\x04\n\x0f\x42ulkOrPlanetoid\x12#\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x15.BulkOrPlanetoid.Meta\x12,\n\thead_node\x18\x02 \x01(\x0b\x32\x19.BulkOrPlanetoid.HeadNode\x12#\n\x1b\x66or_oriented_bounding_box_1\x18\x03 \x03(\x01\x12\x1a\n\x12meters_per_texel_1\x18\x04 \x03(\x02\x12\x1d\n\x15\x64\x65\x66\x61ult_imagery_epoch\x18\x05 \x01(\x03\x12>\n\x16\x64\x65\x66\x61ult_texture_format\x18\x06 \x01(\x0e\x32\x1e.BulkOrPlanetoid.TextureFormat\x1a\'\n\x08HeadNode\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\r\n\x05\x65poch\x18\x02 \x01(\x03\x1a\xbc\x01\n\x04Meta\x12\x0f\n\x07path_id\x18\x01 \x01(\x05\x12\r\n\x05\x65poch\x18\x02 \x01(\x05\x12#\n\x1b\x66or_oriented_bounding_box_2\x18\x03 \x01(\x0c\x12\x1a\n\x12meters_per_texel_2\x18\x04 \x01(\x02\x12\x1b\n\x13\x62ulk_metadata_epoch\x18\x05 \x01(\x05\x12\x36\n\x0etexture_format\x18\x08 \x01(\x0e\x32\x1e.BulkOrPlanetoid.TextureFormat\")\n\rTextureFormat\x12\x05\n\x01_\x10\x00\x12\x07\n\x03JPG\x10\x01\x12\x08\n\x04\x44XT1\x10)b\x06proto3')
)



_BULKORPLANETOID_TEXTUREFORMAT = _descriptor.EnumDescriptor(
  name='TextureFormat',
  full_name='BulkOrPlanetoid.TextureFormat',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='_', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JPG', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DXT1', index=2, number=41,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=526,
  serialized_end=567,
)
_sym_db.RegisterEnumDescriptor(_BULKORPLANETOID_TEXTUREFORMAT)


_BULKORPLANETOID_HEADNODE = _descriptor.Descriptor(
  name='HeadNode',
  full_name='BulkOrPlanetoid.HeadNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='BulkOrPlanetoid.HeadNode.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='epoch', full_name='BulkOrPlanetoid.HeadNode.epoch', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=333,
)

_BULKORPLANETOID_META = _descriptor.Descriptor(
  name='Meta',
  full_name='BulkOrPlanetoid.Meta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path_id', full_name='BulkOrPlanetoid.Meta.path_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='epoch', full_name='BulkOrPlanetoid.Meta.epoch', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='for_oriented_bounding_box_2', full_name='BulkOrPlanetoid.Meta.for_oriented_bounding_box_2', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meters_per_texel_2', full_name='BulkOrPlanetoid.Meta.meters_per_texel_2', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bulk_metadata_epoch', full_name='BulkOrPlanetoid.Meta.bulk_metadata_epoch', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='texture_format', full_name='BulkOrPlanetoid.Meta.texture_format', index=5,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=524,
)

_BULKORPLANETOID = _descriptor.Descriptor(
  name='BulkOrPlanetoid',
  full_name='BulkOrPlanetoid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='BulkOrPlanetoid.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='head_node', full_name='BulkOrPlanetoid.head_node', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='for_oriented_bounding_box_1', full_name='BulkOrPlanetoid.for_oriented_bounding_box_1', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meters_per_texel_1', full_name='BulkOrPlanetoid.meters_per_texel_1', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='default_imagery_epoch', full_name='BulkOrPlanetoid.default_imagery_epoch', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='default_texture_format', full_name='BulkOrPlanetoid.default_texture_format', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_BULKORPLANETOID_HEADNODE, _BULKORPLANETOID_META, ],
  enum_types=[
    _BULKORPLANETOID_TEXTUREFORMAT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=567,
)

_BULKORPLANETOID_HEADNODE.containing_type = _BULKORPLANETOID
_BULKORPLANETOID_META.fields_by_name['texture_format'].enum_type = _BULKORPLANETOID_TEXTUREFORMAT
_BULKORPLANETOID_META.containing_type = _BULKORPLANETOID
_BULKORPLANETOID.fields_by_name['data'].message_type = _BULKORPLANETOID_META
_BULKORPLANETOID.fields_by_name['head_node'].message_type = _BULKORPLANETOID_HEADNODE
_BULKORPLANETOID.fields_by_name['default_texture_format'].enum_type = _BULKORPLANETOID_TEXTUREFORMAT
_BULKORPLANETOID_TEXTUREFORMAT.containing_type = _BULKORPLANETOID
DESCRIPTOR.message_types_by_name['BulkOrPlanetoid'] = _BULKORPLANETOID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BulkOrPlanetoid = _reflection.GeneratedProtocolMessageType('BulkOrPlanetoid', (_message.Message,), dict(

  HeadNode = _reflection.GeneratedProtocolMessageType('HeadNode', (_message.Message,), dict(
    DESCRIPTOR = _BULKORPLANETOID_HEADNODE,
    __module__ = 'proto.BulkOrPlanetoid_pb2'
    # @@protoc_insertion_point(class_scope:BulkOrPlanetoid.HeadNode)
    ))
  ,

  Meta = _reflection.GeneratedProtocolMessageType('Meta', (_message.Message,), dict(
    DESCRIPTOR = _BULKORPLANETOID_META,
    __module__ = 'proto.BulkOrPlanetoid_pb2'
    # @@protoc_insertion_point(class_scope:BulkOrPlanetoid.Meta)
    ))
  ,
  DESCRIPTOR = _BULKORPLANETOID,
  __module__ = 'proto.BulkOrPlanetoid_pb2'
  # @@protoc_insertion_point(class_scope:BulkOrPlanetoid)
  ))
_sym_db.RegisterMessage(BulkOrPlanetoid)
_sym_db.RegisterMessage(BulkOrPlanetoid.HeadNode)
_sym_db.RegisterMessage(BulkOrPlanetoid.Meta)


# @@protoc_insertion_point(module_scope)
